#

OBJDIR=.\obj

OBJ      = "$(OBJDIR)/sizeof.obj" \
        "$(OBJDIR)/pbeginf.obj" \
        "$(OBJDIR)/drand48.obj" \
        "$(OBJDIR)/pfilecopy.obj" \
        "$(OBJDIR)/clustercheck.obj" \
        "$(OBJDIR)/p2p.obj" \
        "$(OBJDIR)/evon.obj" \
        "$(OBJDIR)/misc.obj" \
        "$(OBJDIR)/random.obj" \
        "$(OBJDIR)/collect.obj" \
        "$(OBJDIR)/nxtval-armci.obj" \
        "$(OBJDIR)/memalign.obj" \
        "$(OBJDIR)/wrap.obj" \
        "$(OBJDIR)/evlog.obj"

HEADERS = sndrcv.h srftoc.h msgtypesc.h msgtypesf.h tcgmsg.fh

LOC_DEFINES = -DARMCI
LOC_INCLUDES = -I..\include -I$(MPI_INCLUDE) -I..\armci\src
INCDIR = ..\include

LIBRARY = tcgmsg-mpi.lib
LIB_DISTRIB = ..\lib\win32


!INCLUDE ..\config\NTmakefile.h
!INCLUDE ..\config\NTmakelib.h

LIBS = ..\lib\win32\armci.lib $(MPI) wsock32.lib

testf.exe: .\obj\testf.obj .\obj\checkbyte.obj $(LIBRARY_PATH)
	$(FC) $(FOPT)  -I. /Fetestf.exe $** $(LIBS)

test.exe: .\obj\test.obj .\obj\checkbyte.obj $(LIBRARY_PATH)
	$(CC) $(COPT) /Fetest.exe $** $(LIBS) libf.lib
