# makefile for Windows nmake
# JN

OBJDIR=.\obj

OBJ = $(OBJDIR)\shared.files.obj \
   $(OBJDIR)\sf_fortran.obj 

HEADERS      = sf.h sf.fh

LOC_INCLUDES = -I..\..\include
INCDIR = ..\..\include

LIBRARY = sf.lib
LIB_DISTRIB = ..\..\lib\win32

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h


LIBS = /MT $(LIB_DISTRIB)\pario.lib\
 $(LIB_DISTRIB)\global.lib  $(LIB_DISTRIB)\tcgmsg-mpi.lib\
 $(LIB_DISTRIB)\ma.lib  $(LIB_DISTRIB)\linalg.lib\
 $(LIB_DISTRIB)\armci.lib $(MPI) wsock32.lib

#test.exe: $(OBJDIR)\test.obj
#        $(FC) $(FOPT) /Fetest.exe $** $(LIBS)
