#define  GA_acc                    ga_acc_
#define  GA_access                 ga_access_
#define  GA_brdcst                 ga_brdcst_
#define  GA_check_handle           ga_check_handle_
#define  GA_compare_distr          ga_compare_distr_
#define  GA_copy                   ga_copy_
#define  GA_copy_patch             ga_copy_patch
#define  GA_copy_patch_dp          ga_copy_patch_dp
#define  GA_create                 ga_create
#define  GA_create_irreg           ga_create_irreg
#define  GA_add                    ga_add_
#define  GA_add_patch              ga_add_patch_
#define  GA_ddot                   ga_ddot_
#define  GA_ddot_patch             ga_ddot_patch
#define  GA_zdot                   ga_zdot_
#define  GA_idot                   ga_idot_
#define  GA_zdot_patch             ga_zdot_patch
#define  GA_ddot_patch_dp          ga_ddot_patch_dp
#define  GA_destroy                ga_destroy_
#define  GA_dgop                   ga_dgop_
#define  GA_dgemm                  ga_dgemm_
#define  GA_diag                   ga_diag_
#define  GA_diag_reuse             ga_diag_reuse_
#define  GA_diag_std               ga_diag_std_
#define  GA_llt_solve              ga_llt_solve_
#define  GA_lu_solve               ga_lu_solve_alt_
#define  GA_solve                  ga_solve_
#define  GA_spd_invert             ga_spd_invert_
#define  GA_distribution           ga_distribution_
#define  GA_scale                  ga_scale_
#define  GA_scale_patch            ga_scale_patch_
#define  GA_duplicate              ga_duplicate
#define  GA_error                  ga_error
#define  GA_fence                  ga_fence_
#define  GA_gather                 ga_gather_
#define  GA_get                    ga_get_
#define  GA_fill_patch             ga_fill_patch_
#define  GA_igop                   ga_igop_
#define  GA_initialize             ga_initialize_
#define  GA_init_fence             ga_init_fence_
#define  GA_initialize_ltd         ga_initialize_ltd_
#define  GA_inquire                ga_inquire_
#define  GA_inquire_memory         ga_inquire_memory_
#define  GA_inquire_name           ga_inquire_name
#define  GA_list_nodeid            ga_list_nodeid_
#define  GA_locate                 ga_locate_
#define  GA_locate_region          ga_locate_region_
#define  GA_matmul_patch           ga_matmul_patch
#define  GA_mpi_communicator       ga_mpi_communicator
#define  GA_nnodes                 ga_nnodes_
#define  GA_nodeid                 ga_nodeid_
#define  GA_print                  ga_print_
#define  GA_print_patch            ga_print_patch_
#define  GA_print_stats            ga_print_stats_
#define  GA_proc_topology          ga_proc_topology_
#define  GA_put                    ga_put_
#define  GA_read_inc               ga_read_inc_
#define  GA_release                ga_release_
#define  GA_release_update         ga_release_update_
#define  GA_scatter                ga_scatter_
#define  GA_scatter_acc            ga_scatter_acc_
#define  GA_sort_scat_dbl          ga_sort_scat_dbl_
#define  GA_sort_scat_int          ga_sort_scat_int_
#define  GA_sync                   ga_sync_
#define  GA_summarize              ga_summarize_
#define  GA_symmetrize             ga_symmetrize_
#define  GA_terminate              ga_terminate_
#define  GA_transpose              ga_transpose_
#define  GA_uses_ma                ga_uses_ma_
#define  GA_verify_handle          ga_verify_handle_
#define  GA_zero                   ga_zero_
#define  GA_ndim                   ga_ndim_
#define  GA_print_distribution     ga_print_distribution_

#define  GA_create_mutexes         ga_create_mutexes_
#define  GA_destroy_mutexes        ga_destroy_mutexes_
#define  GA_lock                   ga_lock_
#define  GA_unlock                 ga_unlock_
#define  GA_valid_handle           ga_valid_handle_
#define  GA_set_memory_limit       ga_set_memory_limit_

