/*$Id: cray.names.h,v 1.15 1996-07-19 20:05:27 d3h325 Exp $*/
#define  ga_acc_                   GA_ACC
#define  ga_access_                GA_ACCESS
#define  ga_brdcst_                GA_BRDCST
#define  ga_check_handle_          GA_CHECK_HANDLE
#define  ga_compare_distr_         GA_COMPARE_DISTR
#define  ga_copy_                  GA_COPY
#define  ga_copy_patch_            GA_COPY_PATCH
#define  ga_create_                GA_CREATE
#define  ga_create_irreg_          GA_CREATE_IRREG
#define  ga_add_                   GA_ADD
#define  ga_add_patch_             GA_ADD_PATCH
#define  ga_ddot_                  GA_DDOT
#define  ga_zdot_                  GA_ZDOT
#define  ga_destroy_               GA_DESTROY
#define  ga_fence_                 GA_FENCE
#define  ga_gather_                GA_GATHER
#define  ga_dgop_                  GA_DGOP
#define  ga_distribution_          GA_DISTRIBUTION
#define  ga_duplicate_             GA_DUPLICATE
#define  ga_error_                 GA_ERROR
#define  ga_get_                   GA_GET
#define  ga_fill_patch_            GA_FILL_PATCH
#define  ga_igop_                  GA_IGOP
#define  ga_initialize_            GA_INITIALIZE
#define  ga_init_fence_            GA_INIT_FENCE
#define  ga_initialize_ltd_        GA_INITIALIZE_LTD
#define  ga_inquire_               GA_INQUIRE
#define  ga_inquire_name_          GA_INQUIRE_NAME
#define  ga_inquire_memory_        GA_INQUIRE_MEMORY
#define  ga_list_nodeid_           GA_LIST_NODEID
#define  ga_locate_                GA_LOCATE
#define  ga_locate_region_         GA_LOCATE_REGION
#define  ga_matmul_patch_          GA_MATMUL_PATCH
#define  ga_memory_limited_        GA_MEMORY_LIMITED
#define  ga_memory_avail_          GA_MEMORY_AVAIL
#define  ga_nnodes_                GA_NNODES
#define  ga_nodeid_                GA_NODEID
#define  ga_net_nnodes_            GA_NET_NNODES
#define  ga_net_nodeid_            GA_NET_NODEID
#define  ga_print_                 GA_PRINT
#define  ga_print_patch_           GA_PRINT_PATCH
#define  ga_put_                   GA_PUT
#define  ga_read_inc_              GA_READ_INC
#define  ga_reinit_handler_        GA_REINIT_HANDLER
#define  ga_release_               GA_RELEASE
#define  ga_release_update_        GA_RELEASE_UPDATE
#define  ga_server_                GA_SERVER
#define  ga_sort_scat2_            GA_SORT_SCAT2
#define  ga_sync_                  GA_SYNC
#define  ga_scale_                 GA_SCALE
#define  ga_scale_patch_           GA_SCALE_PATCH
#define  ga_scatter_               GA_SCATTER
#define  ga_terminate_             GA_TERMINATE
#define  ga_uses_ma_               GA_USES_MA
#define  ga_zero_                  GA_ZERO
#define  ga_verify_handle_         GA_VERIFY_HANDLE
#define  ga_copy_patch_dp_         GA_COPY_PATCH_DP
#define  ga_ddot_patch_dp_         GA_DDOT_PATCH_DP
#define  ga_proc_topology_         GA_PROC_TOPOLOGY
#define  ga_symmetrize_            GA_SYMMETRIZE
#define  ga_transpose_             GA_TRANSPOSE

#define  gai_dot_patch_            GAI_DOT_PATCH
#define  gai_dot_                  GAI_DOT

#define  synch_                    SYNCH 
#define  nnodes_                   NNODES 
#define  nodeid_                   NODEID 
#define  brdcst_                   BRDCST
#define  dgop_                     DGOP 
#define  igop_                     IGOP 
#define  rcv_                      RCV 
#define  snd_                      SND 
#define  pend_                     PEND 
#define  probe_                    PROBE
#define  waitcom_                  WAITCOM
#define  tcgtime_                  TCGTIME 

#define  ga_ma_base_address_       GA_MA_BASE_ADDRESS 
#define  ga_ma_sizeof_             GA_MA_SIZEOF
#define  ga_ma_get_ptr_            GA_MA_GET_PTR
#define  ga_ma_diff_               GA_MA_DIFF
#define  dgemm_                    DGEMM
