/*$Id: cray.names.h,v 1.6 1995-02-15 17:55:21 d3h325 Exp $*/
#define  ga_acc_                   GA_ACC
#define  ga_access_                GA_ACCESS
#define  ga_brdcst_                GA_BRDCST
#define  ga_check_handle_          GA_CHECK_HANDLE
#define  ga_compare_distr_         GA_COMPARE_DISTR
#define  ga_copy_                  GA_COPY
#define  ga_copy_from_patch_       GA_COPY_FROM_PATCH
#define  ga_copy_patch_            GA_COPY_PATCH
#define  ga_copy_to_patch_         GA_COPY_TO_PATCH
#define  ga_create_                GA_CREATE
#define  ga_create_irreg_          GA_CREATE_IRREG
#define  ga_dadd_                  GA_DADD
#define  ga_dadd_patch_            GA_DADD_PATCH
#define  ga_ddot_                  GA_DDOT
#define  ga_ddot_patch_            GA_DDOT_PATCH
#define  ga_destroy_               GA_DESTROY
#define  ga_dfill_patch_           GA_DFILL_PATCH
#define  ga_gather_                GA_GATHER
#define  ga_dgop_                  GA_DGOP
#define  ga_distribution_          GA_DISTRIBUTION
#define  ga_dscal_                 GA_DSCAL
#define  ga_dscal_patch_           GA_DSCAL_PATCH
#define  ga_scatter_               GA_SCATTER
#define  ga_duplicate_             GA_DUPLICATE
#define  ga_error_                 GA_ERROR
#define  ga_get_                   GA_GET
#define  ga_ifill_patch_           GA_IFILL_PATCH
#define  ga_igop_                  GA_IGOP
#define  ga_init_handler_          GA_INIT_HANDLER
#define  ga_initialize_            GA_INITIALIZE
#define  ga_inquire_               GA_INQUIRE
#define  ga_inquire_name_          GA_INQUIRE_NAME
#define  ga_list_nodeid_           GA_LIST_NODEID
#define  ga_locate_                GA_LOCATE
#define  ga_locate_region_         GA_LOCATE_REGION
#define  ga_mask_                  GA_MASK
#define  ga_matmul_patch_          GA_MATMUL_PATCH
#define  ga_nnodes_                GA_NNODES
#define  ga_nodeid_                GA_NODEID
#define  ga_print_                 GA_PRINT
#define  ga_print_patch_           GA_PRINT_PATCH
#define  ga_put_                   GA_PUT
#define  ga_read_inc_              GA_READ_INC
#define  ga_reinit_handler_        GA_REINIT_HANDLER
#define  ga_release_               GA_RELEASE
#define  ga_release_update_        GA_RELEASE_UPDATE
#define  ga_server_                GA_SERVER
#define  ga_sort_scat2_            GA_SORT_SCAT2
#define  ga_sync_                  GA_SYNC
#define  ga_terminate_             GA_TERMINATE
#define  ga_zero_                  GA_ZERO
#define  ga_verify_handle_         GA_VERIFY_HANDLE

#define  synch_                    SYNCH 
#define  nnodes_                   NNODES 
#define  nodeid_                   NODEID 
#define  brdcst_                   BRDCST
#define  dgop_                     DGOP 
#define  igop_                     IGOP 
#define  rcv_                      RCV 
#define  snd_                      SND 
#define  pend_                     PEND 
#define  waitcom_                  WAITCOM
#define  tcgtime_                  TCGTIME 
#define  ma__base_address_         MA__BASE_ADDRESS 
#define  ma__sizeof_               MA__SIZEOF
#define  ma__get_ptr_              MA__GET_PTR
#define  ma__diff_                 MA__DIFF
#define  dgemm_                    DGEMM
