#
#	$Id: MakeFile,v 1.27 2003-02-20 22:59:41 edo Exp $
#

OBJDIR=.\obj

#on NT we use MPI
USE_MPI=y

GA_CORE  = $(OBJDIR)\base.obj \
        $(OBJDIR)\onesided.obj \
        $(OBJDIR)\ghosts.obj \
        $(OBJDIR)\collect.obj \
        $(OBJDIR)\global.npatch.obj \
        $(OBJDIR)\global.util.obj \
        $(OBJDIR)\global.periodic.obj \
        $(OBJDIR)\matmul.obj \
        $(OBJDIR)\hsort.scat.obj \
        $(OBJDIR)\global.nalg.obj \
        $(OBJDIR)\decomp.obj \
        $(OBJDIR)\fort.obj \
        $(OBJDIR)\capi.obj \
        $(OBJDIR)\ga_symmetr.obj\
        $(OBJDIR)\datatypes.obj\
        $(OBJDIR)\sparse.obj \
        $(OBJDIR)\select.obj \
        $(OBJDIR)\DP.obj \
        $(OBJDIR)\xgemm.obj \
        $(OBJDIR)\matrix.obj \
        $(OBJDIR)\elem_alg.obj \
        $(OBJDIR)\nbutil.obj \
        $(OBJDIR)\ga_malloc.obj \
	$(OBJDIR)\ga_solve_seq.obj 
	
!IFDEF GA_USE_VAMPIR
GA_EXTRA = $(OBJDIR)\ga_vampir.obj
!ENDIF

# Linear Algebra
!IFNDEF GA_C_CORE
GA_LIN_ALG = $(OBJDIR)\rsg.obj $(OBJDIR)\ga_diag_seq.obj
LOC_DEFINES = -DARMCI
!ELSE
LOC_DEFINES = -DARMCI -DGA_C_CORE
!ENDIF

# ga_transpose.o
!IF ("$(DIAG)" == "PAR")
GA_DIAG = $(OBJDIR)\ga_diag.obj
!ELSE
GA_DIAG = $(OBJDIR)\peigstubs.obj
!ENDIF
!IFDEF USE_SCALAPACK
GA_SP = $(OBJDIR)\scalapack.obj
!ELSE
GA_SP = $(OBJDIR)\sclstubs.obj
!ENDIF

OBJ = $(GA_CORE) $(GA_EXTRA) $(GA_LIN_ALG) $(GA_DIAG) $(GA_SP)


# you can restore the old threshold for default decomposition in ga_create
# by uncommenting the following statement
# LOC_DEFINES += -DOLD_DEFAULT_BLK

INCDIR = ..\..\include
LOC_INCLUDES = -I..\..\include -I$(MPI_INCLUDE) -I..\..\armci\src

HEADERS = global.h ga.h global.fh c.names.h #cray.names.h
LIBRARY = global.lib
LIB_DISTRIB = ..\..\lib\win32

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h
