/* $Id: onesided.c,v 1.15 2001-12-04 22:20:30 d3g293 Exp $ */
/* 
 * module: onesided.c
 * author: Jarek Nieplocha
 * description: implements GA primitive communication operations --
 *              accumulate, scatter, gather, read&increment & synchronization 
 * 
 * DISCLAIMER
 *
 * This material was prepared as an account of work sponsored by an
 * agency of the United States Government.  Neither the United States
 * Government nor the United States Department of Energy, nor Battelle,
 * nor any of their employees, MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
 * ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY,
 * COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT,
 * SOFTWARE, OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE WOULD NOT
 * INFRINGE PRIVATELY OWNED RIGHTS.
 *
 *
 * ACKNOWLEDGMENT
 *
 * This software and its documentation were produced with United States
 * Government support under Contract Number DE-AC06-76RLO-1830 awarded by
 * the United States Department of Energy.  The United States Government
 * retains a paid-up non-exclusive, irrevocable worldwide license to
 * reproduce, prepare derivative works, perform publicly and display
 * publicly by or for the US Government, including the right to
 * distribute to other US Government contractors.
 */

 
/*#define PERMUTE_PIDS */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <assert.h>
#include "globalp.h"
#include "base.h"
#include "armci.h"
#include "macdecls.h"

#define DEBUG 0
#define USE_MALLOC 1
#define INVALID_MA_HANDLE -1 
#define NEAR_INT(x) (x)< 0.0 ? ceil( (x) - 0.5) : floor((x) + 0.5)

#if !defined(CRAY_YMP)
#define BYTE_ADDRESSABLE_MEMORY
#endif

int    ProcListPerm[MAX_NPROC];            /* permuted list of processes */
static global_array_t *GA = _ga_main_data_structure;


/*uncomment line below to verify consistency of MA in every sync */
/*#define CHECK_MA yes */

char *fence_array;
static int GA_fence_set=0;
Integer *_ga_map;       /* used in get/put/acc */

extern void ga_sort_scat(Integer*,Void*,Integer*,Integer*,Integer*, Integer);
extern void ga_sort_gath_(Integer*, Integer*, Integer*, Integer*);
extern void armci_read_strided(void*, int, int*, int*, char*);
extern void armci_write_strided(void*, int, int*, int*, char*);

/***************************************************************************/

/*\ SYNCHRONIZE ALL THE PROCESSES
\*/
void FATR ga_sync_()
{
extern int GA_fence_set;
#ifdef CHECK_MA
Integer status;
#endif

       ARMCI_AllFence();
       ga_msg_sync_();
       if(GA_fence_set)bzero(fence_array,(int)GAnproc);
       GA_fence_set=0;
#ifdef CHECK_MA
       status = MA_verify_allocator_stuff();
#endif
}


/*\ wait until requests intiated by calling process are completed
\*/
void FATR ga_fence_()
{
    int proc;
    if(GA_fence_set<1)ga_error("ga_fence: fence not initialized",0);
    GA_fence_set--;
    for(proc=0;proc<GAnproc;proc++)if(fence_array[proc])ARMCI_Fence(proc);
    bzero(fence_array,(int)GAnproc);
}

/*\ initialize tracing of request completion
\*/
void FATR ga_init_fence_()
{
    GA_fence_set++;
}

void gai_init_onesided()
{
    _ga_map = (Integer*)malloc((size_t)(GAnproc*2*MAXDIM +1)*sizeof(Integer));
    if(!_ga_map) ga_error("ga_init:malloc failed (_ga_map)",0);
    fence_array = calloc((size_t)GAnproc,1);
    if(!fence_array) ga_error("ga_init:calloc failed",0);
}


/*\ prepare permuted list of processes for remote ops
\*/
#define gaPermuteProcList(nproc)\
{\
  if((nproc) ==1) ProcListPerm[0]=0; \
  else{\
    int _i, iswap, temp;\
    if((nproc) > GAnproc) ga_error("permute_proc: error ", (nproc));\
\
    /* every process generates different random sequence */\
    (void)srand((unsigned)GAme); \
\
    /* initialize list */\
    for(_i=0; _i< (nproc); _i++) ProcListPerm[_i]=_i;\
\
    /* list permutation generated by random swapping */\
    for(_i=0; _i< (nproc); _i++){ \
      iswap = (int)(rand() % (nproc));  \
      temp = ProcListPerm[iswap]; \
      ProcListPerm[iswap] = ProcListPerm[_i]; \
      ProcListPerm[_i] = temp; \
    } \
  }\
}
     




/*\ internal malloc that bypasses MA and uses internal buf when possible
\*/
#define MBUFLEN 256
#define MBUF_LEN MBUFLEN+2
static double ga_int_malloc_buf[MBUF_LEN];
static int mbuf_used=0;
#define MBUF_GUARD -1998.1998
void *gai_malloc(int bytes)
{
    void *ptr;
    if(!mbuf_used && bytes <= MBUF_LEN){
       if(DEBUG){
          ga_int_malloc_buf[0]= MBUF_GUARD;
          ga_int_malloc_buf[MBUFLEN]= MBUF_GUARD;
       }
       ptr = ga_int_malloc_buf+1;
       mbuf_used++;
    }else{
        Integer handle, idx, elems = (bytes+sizeof(double)-1)/sizeof(double)+1; 
        if(MA_push_get(MT_DBL, elems, "GA malloc temp", &handle, &idx)){
            MA_get_pointer(handle, &ptr);
            *((Integer*)ptr)= handle;
            ptr = ((double*)ptr)+ 1;  /*needs sizeof(double)>=sizeof(Integer) */
        }else
            ptr=NULL;
    }
    return ptr;
}

void gai_free(void *ptr)
{
    if(ptr == (ga_int_malloc_buf+1)){
        if(DEBUG){
          assert(ga_int_malloc_buf[0]== MBUF_GUARD);
          assert(ga_int_malloc_buf[MBUFLEN]== MBUF_GUARD);
          assert(mbuf_used ==1);
        }
        mbuf_used =0;
    }else{
        Integer handle= *( (Integer*) (-1 + (double*)ptr));
        if(!MA_pop_stack(handle)) ga_error("gai_free:MA_pop_stack failed",0);
    }
}

        


#define gaShmemLocation(proc, g_a, _i, _j, ptr_loc, _pld)                      \
{                                                                              \
Integer _ilo, _ihi, _jlo, _jhi, offset, proc_place, g_handle=(g_a)+GA_OFFSET;  \
Integer _lo[2], _hi[2];                                                        \
Integer _iw = GA[g_handle].width[0];                                           \
Integer _jw = GA[g_handle].width[1];                                           \
                                                                               \
      ga_ownsM(g_handle, (proc),_lo,_hi);                                      \
      _ilo = _lo[0]; _ihi=_hi[0];                                              \
      _jlo = _lo[1]; _jhi=_hi[1];                                              \
                                                                               \
      if((_i)<_ilo || (_i)>_ihi || (_j)<_jlo || (_j)>_jhi){                    \
       sprintf(err_string,"%s:p=%ld invalid i/j (%ld,%ld)><(%ld:%ld,%ld:%ld)", \
                 "gaShmemLocation", proc, (_i),(_j), _ilo, _ihi, _jlo, _jhi);  \
          ga_error(err_string, g_a );                                          \
      }                                                                        \
      offset = ((_i)-_ilo+_iw) + (_ihi-_ilo+1+2*_iw)*((_j)-_jlo+_jw);          \
                                                                               \
      /* find location of the proc in current cluster pointer array */         \
      proc_place =  proc;                                                      \
      *(ptr_loc) = GA[g_handle].ptr[proc_place] +                              \
                   offset*GAsizeofM(GA[g_handle].type);                        \
      *(_pld) = _ihi-_ilo+1+2*_iw;                                             \
}


#define gaCheckSubscriptM(subscr, lo, hi, ndim)                             \
{                                                                              \
Integer _d;                                                                    \
   for(_d=0; _d<  ndim; _d++)                                                  \
      if( subscr[_d]<  lo[_d] ||  subscr[_d]>  hi[_d]){                  \
        sprintf(err_string,"check subscript failed:%ld not in (%ld:%ld) dim=", \
                  subscr[_d],  lo[_d],  hi[_d]);                            \
          ga_error(err_string, _d);                                            \
      }\
}

/*\ Return pointer (ptr_loc) to location in memory of element with subscripts
 *  (subscript). Also return physical dimensions of array in memory in ld.
\*/
#define gam_Location(proc, g_handle,  subscript, ptr_loc, ld)                  \
{                                                                              \
Integer _offset=0, _d, _w, _factor=1, _last=GA[g_handle].ndim-1;               \
Integer _lo[MAXDIM], _hi[MAXDIM];                                              \
                                                                               \
      ga_ownsM(g_handle, proc, _lo, _hi);                                      \
      gaCheckSubscriptM(subscript, _lo, _hi, GA[g_handle].ndim);               \
      if(_last==0) ld[0]=_hi[0]- _lo[0]+1+2*GA[g_handle].width[0];             \
      for(_d=0; _d < _last; _d++)            {                                 \
          _w = GA[g_handle].width[_d];                                         \
          _offset += (subscript[_d]-_lo[_d]+_w) * _factor;                     \
          ld[_d] = _hi[_d] - _lo[_d]+1+2*_w;                                   \
          _factor *= ld[_d];                                                   \
      }                                                                        \
      _offset += (subscript[_last]-_lo[_last]+GA[g_handle].width[_last])       \
               * _factor;                                                      \
      *(ptr_loc) =  GA[g_handle].ptr[proc]+_offset*GA[g_handle].elemsize;      \
}


/*\ Just return pointer (ptr_loc) to location in memory of element with
 *  subscripts (subscript).
\*/
#define gam_Loc_ptr(proc, g_handle,  subscript, ptr_loc)                      \
{                                                                             \
Integer _offset=0, _d, _w, _factor=1, _last=GA[g_handle].ndim-1;              \
Integer _lo[MAXDIM], _hi[MAXDIM];                                             \
                                                                              \
      ga_ownsM(g_handle, proc, _lo, _hi);                                     \
      gaCheckSubscriptM(subscript, _lo, _hi, GA[g_handle].ndim);              \
      for(_d=0; _d < _last; _d++)            {                                \
          _w = GA[g_handle].width[_d];                                        \
          _offset += (subscript[_d]-_lo[_d]+_w) * _factor;                    \
          _factor *= _hi[_d] - _lo[_d]+1+2*_w;                                \
      }                                                                       \
      _offset += (subscript[_last]-_lo[_last]+GA[g_handle].width[_last])      \
               * _factor;                                                     \
      *(ptr_loc) =  GA[g_handle].ptr[proc]+_offset*GA[g_handle].elemsize;     \
}

#define ga_check_regionM(g_a, ilo, ihi, jlo, jhi, string){                     \
   if (*(ilo) <= 0 || *(ihi) > GA[GA_OFFSET + *(g_a)].dims[0] ||               \
       *(jlo) <= 0 || *(jhi) > GA[GA_OFFSET + *(g_a)].dims[1] ||               \
       *(ihi) < *(ilo) ||  *(jhi) < *(jlo)){                                   \
       sprintf(err_string,"%s:req(%ld:%ld,%ld:%ld) out of range (1:%ld,1:%ld)",\
               string, *(ilo), *(ihi), *(jlo), *(jhi),                         \
               GA[GA_OFFSET + *(g_a)].dims[0], GA[GA_OFFSET + *(g_a)].dims[1]);\
       ga_error(err_string, *(g_a));                                           \
   }                                                                           \
}



#define gam_GetRangeFromMap0(p, ndim, plo, phi, proc){\
Integer   _mloc = p* (ndim *2 +1);\
          *plo  = (Integer*)_ga_map + _mloc;\
          *phi  = *plo + ndim;\
          *proc = *phi[ndim]; /* proc is immediately after hi */\
}

#define gam_GetRangeFromMap(p, ndim, plo, phi){\
Integer   _mloc = p* ndim *2;\
          *plo  = (Integer*)_ga_map + _mloc;\
          *phi  = *plo + ndim;\
}

/* compute index of point subscripted by plo relative to point
   subscripted by lo, for a block with dimensions dims */
#define gam_ComputePatchIndex(ndim, lo, plo, dims, pidx){\
Integer _d, _factor;\
          *pidx = plo[0] -lo[0];\
          for(_d= 0,_factor=1; _d< ndim -1; _d++){\
             _factor *= dims[_d];\
             *pidx += _factor * (plo[_d+1]-lo[_d+1]);\
          }\
}

/*\ PUT A 2-DIMENSIONAL PATCH OF DATA INTO A GLOBAL ARRAY
\*/
void FATR nga_put_(Integer *g_a, 
                   Integer *lo,
                   Integer *hi,
                   void    *buf,
                   Integer *ld)
{
Integer  p, np, handle=GA_OFFSET + *g_a;
Integer  idx, elems, size;
int proc, ndim;

      GA_PUSH_NAME("nga_put");

      if(!nga_locate_region_(g_a, lo, hi, _ga_map, GA_proclist, &np ))
          ga_RegionError(ga_ndim_(g_a), lo, hi, *g_a);

      size = GA[handle].elemsize;
      ndim = GA[handle].ndim;

      gam_CountElems(ndim, lo, hi, &elems);
      GAbytes.puttot += (double)size*elems;
      GAstat.numput++;

      gaPermuteProcList(np);
      for(idx=0; idx< np; idx++){
          Integer ldrem[MAXDIM];
          int stride_rem[MAXDIM], stride_loc[MAXDIM], count[MAXDIM];
          Integer idx_buf, *plo, *phi;
          char *pbuf, *prem;

          p = (Integer)ProcListPerm[idx];
          gam_GetRangeFromMap(p, ndim, &plo, &phi);
          proc = (int)GA_proclist[p];

          gam_Location(proc,handle, plo, &prem, ldrem); 

          /* find the right spot in the user buffer */
          gam_ComputePatchIndex(ndim,lo, plo, ld, &idx_buf);
          pbuf = size*idx_buf + (char*)buf;        

          gam_ComputeCount(ndim, plo, phi, count); 

          /* scale number of rows by element size */
          count[0] *= size; 
          gam_setstride(ndim, size, ld, ldrem, stride_rem, stride_loc);

          if(GA_fence_set)fence_array[proc]=1;
#ifdef PERMUTE_PIDS
    if(GA_Proc_list){
       /* fprintf(stderr,"permuted %d %d\n",proc,GA_inv_Proc_list[proc]);*/
       proc = GA_inv_Proc_list[proc];
    }
#endif

          if(proc == GAme){
             gam_CountElems(ndim, plo, phi, &elems);
             GAbytes.putloc += (double)size*elems;
          }
          ARMCI_PutS(pbuf, stride_loc, prem, stride_rem, count, ndim -1, proc);

      }

      GA_POP_NAME;
}



void FATR  ga_put_(g_a, ilo, ihi, jlo, jhi, buf, ld)
   Integer  *g_a,  *ilo, *ihi, *jlo, *jhi,  *ld;
   Void  *buf;
{
Integer lo[2], hi[2];

#ifdef GA_TRACE
   trace_stime_();
#endif

   lo[0]=*ilo;
   lo[1]=*jlo;
   hi[0]=*ihi;
   hi[1]=*jhi;
   nga_put_(g_a, lo, hi, buf, ld);

#ifdef GA_TRACE
   trace_etime_();
   op_code = GA_OP_PUT; 
   trace_genrec_(g_a, ilo, ihi, jlo, jhi, &op_code);
#endif
}



/*\ GET AN N-DIMENSIONAL PATCH OF DATA FROM A GLOBAL ARRAY
\*/
void FATR nga_get_(Integer *g_a,
                   Integer *lo,
                   Integer *hi,
                   void    *buf,
                   Integer *ld)
{
Integer  p, np, handle=GA_OFFSET + *g_a;
Integer  idx, elems, size;
int proc, ndim;

      GA_PUSH_NAME("nga_get");

      /* Locate the processors containing some portion of the patch
         specified by lo and hi and return the results in _ga_map,
         GA_proclist, and np. GA_proclist contains a list of processors
         containing some portion of the patch, _ga_map contains
         the lower and upper indices of the portion of the patch held
         by a given processor, and np contains the total number of
         processors that contain some portion of the patch.
      */
      if(!nga_locate_region_(g_a, lo, hi, _ga_map, GA_proclist, &np ))
          ga_RegionError(ga_ndim_(g_a), lo, hi, *g_a);

      size = GA[handle].elemsize;
      ndim = GA[handle].ndim;

      /* get total size of patch */
      gam_CountElems(ndim, lo, hi, &elems);
      GAbytes.gettot += (double)size*elems;
      GAstat.numget++;

      gaPermuteProcList(np);
      for(idx=0; idx< np; idx++){
          Integer ldrem[MAXDIM];
          int stride_rem[MAXDIM], stride_loc[MAXDIM], count[MAXDIM];
          Integer idx_buf, *plo, *phi;
          char *pbuf, *prem;

          p = (Integer)ProcListPerm[idx];
          /* Find portion of patch held by processor p and return
             the result in plo and phi. Also get actual processor
             index corresponding to p and store the result in proc. */
          gam_GetRangeFromMap(p, ndim, &plo, &phi);
          proc = (int)GA_proclist[p];

          /* get pointer prem to location indexed by plo. Also get
             leading physical dimensions in memory in ldrem */
          gam_Location(proc,handle, plo, &prem, ldrem);

          /* find the right spot in the user buffer for the point
             subscripted by plo given that the corner of the user
             buffer is subscripted by lo */
          gam_ComputePatchIndex(ndim,lo, plo, ld, &idx_buf);
          pbuf = size*idx_buf + (char*)buf;

          /* compute number of elements in each dimension and store the
             result in count */
          gam_ComputeCount(ndim, plo, phi, count);

          /* Scale first element in count by element size. The ARMCI_GetS
             routine uses this convention to figure out memory sizes.*/
          count[0] *= size; 

          /* Return strides for memory containing global array on remote
             processor indexed by proc (stride_rem) and for local buffer
             buf (stride_loc) */
          gam_setstride(ndim, size, ld, ldrem, stride_rem, stride_loc);

#ifdef PERMUTE_PIDS
          if(GA_Proc_list) proc = GA_inv_Proc_list[proc];
#endif
          if(proc == GAme){
             gam_CountElems(ndim, plo, phi, &elems);
             GAbytes.getloc += (double)size*elems;
          }
          ARMCI_GetS(prem, stride_rem, pbuf, stride_loc, count, ndim -1, proc);

      }

      GA_POP_NAME;
}


void FATR  ga_get_(g_a, ilo, ihi, jlo, jhi, buf, ld)
   Integer  *g_a,  *ilo, *ihi, *jlo, *jhi,  *ld;
   Void  *buf;
{
Integer lo[2], hi[2];

#ifdef GA_TRACE
   trace_stime_();
#endif

   lo[0]=*ilo;
   lo[1]=*jlo;
   hi[0]=*ihi;
   hi[1]=*jhi;
   nga_get_(g_a, lo, hi, buf, ld);

#ifdef GA_TRACE
   trace_etime_();
   op_code = GA_OP_GET;
   trace_genrec_(g_a, ilo, ihi, jlo, jhi, &op_code);
#endif
}



/*\ ACCUMULATE OPERATION FOR A N-DIMENSIONAL PATCH OF GLOBAL ARRAY
 *
 *  g_a += alpha * patch
\*/
void FATR nga_acc_(Integer *g_a,
                   Integer *lo,
                   Integer *hi,
                   void    *buf,
                   Integer *ld,
                   void    *alpha)
{
Integer  p, np, handle=GA_OFFSET + *g_a;
Integer  idx, elems, size, type;
int optype, proc, ndim;

      GA_PUSH_NAME("nga_acc");

      if(!nga_locate_region_(g_a, lo, hi, _ga_map, GA_proclist, &np ))
          ga_RegionError(ga_ndim_(g_a), lo, hi, *g_a);

      size = GA[handle].elemsize;
      type = GA[handle].type;
      ndim = GA[handle].ndim;

      if(type==MT_F_DBL) optype= ARMCI_ACC_DBL;
      else if(type==MT_F_REAL) optype= ARMCI_ACC_FLT;
      else if(type==MT_F_DCPL)optype= ARMCI_ACC_DCP;
      else if(size==sizeof(int))optype= ARMCI_ACC_INT;
      else if(size==sizeof(long))optype= ARMCI_ACC_LNG;
      else ga_error("type not supported",type);

      gam_CountElems(ndim, lo, hi, &elems);
      GAbytes.acctot += (double)size*elems;
      GAstat.numacc++;

      gaPermuteProcList(np);
      for(idx=0; idx< np; idx++){
          Integer ldrem[MAXDIM];
          int stride_rem[MAXDIM], stride_loc[MAXDIM], count[MAXDIM];
          Integer idx_buf, *plo, *phi;
          char *pbuf, *prem;

          p = (Integer)ProcListPerm[idx];
          gam_GetRangeFromMap(p, ndim, &plo, &phi);
          proc = (int)GA_proclist[p];

          gam_Location(proc,handle, plo, &prem, ldrem);

          /* find the right spot in the user buffer */
          gam_ComputePatchIndex(ndim,lo, plo, ld, &idx_buf);
          pbuf = size*idx_buf + (char*)buf;

          gam_ComputeCount(ndim, plo, phi, count);

          /* scale number of rows by element size */
          count[0] *= size;
          gam_setstride(ndim, size, ld, ldrem, stride_rem, stride_loc);

          if(GA_fence_set)fence_array[proc]=1;

#ifdef PERMUTE_PIDS
          if(GA_Proc_list) proc = GA_inv_Proc_list[proc];
#endif
          if(proc == GAme){
             gam_CountElems(ndim, plo, phi, &elems);
             GAbytes.accloc += (double)size*elems;
          }

          ARMCI_AccS(optype, alpha, pbuf, stride_loc, prem, stride_rem, count, ndim-1, proc);

      }

      GA_POP_NAME;
}



void FATR  ga_acc_(g_a, ilo, ihi, jlo, jhi, buf, ld, alpha)
   Integer *g_a, *ilo, *ihi, *jlo, *jhi, *ld;
   void *buf, *alpha;
{
Integer lo[2], hi[2];
#ifdef GA_TRACE
   trace_stime_();
#endif

   lo[0]=*ilo;
   lo[1]=*jlo;
   hi[0]=*ihi;
   hi[1]=*jhi;
   nga_acc_(g_a, lo, hi, buf, ld, alpha);

#ifdef GA_TRACE
   trace_etime_();
   op_code = GA_OP_ACC;
   trace_genrec_(g_a, ilo, ihi, jlo, jhi, &op_code);
#endif
}


void nga_access_ptr(Integer* g_a, Integer lo[], Integer hi[],
                      void* ptr, Integer ld[])

{
char *lptr;
Integer  handle = GA_OFFSET + *g_a;
Integer  ow,i;

   GA_PUSH_NAME("nga_access_ptr");
   if(!nga_locate_(g_a,lo,&ow))ga_error("locate top failed",0);
   if(ow != GAme) ga_error("cannot access top of the patch",ow);
   if(!nga_locate_(g_a,hi, &ow))ga_error("locate bottom failed",0);
   if(ow != GAme) ga_error("cannot access bottom of the patch",ow);

   for (i=0; i<GA[handle].ndim; i++)
       if(lo[i]>hi[i]) {
           ga_RegionError(GA[handle].ndim, lo, hi, *g_a);
       }

   gam_Location(ow,handle, lo, &lptr, ld);
   *(char**)ptr = lptr; 
   GA_POP_NAME;
}

/*\ PROVIDE ACCESS TO A PATCH OF A GLOBAL ARRAY
\*/
void FATR nga_access_(Integer* g_a, Integer lo[], Integer hi[],
                      Integer* index, Integer ld[])
{
char     *ptr;
Integer  handle = GA_OFFSET + *g_a;
Integer  ow,i;
unsigned long    elemsize;
unsigned long    lref, lptr;

   GA_PUSH_NAME("nga_access");
   if(!nga_locate_(g_a,lo,&ow))ga_error("locate top failed",0);
   if(ow != GAme) ga_error("cannot access top of the patch",ow);
   if(!nga_locate_(g_a,hi, &ow))ga_error("locate bottom failed",0);
   if(ow != GAme) ga_error("cannot access bottom of the patch",ow);

   for (i=0; i<GA[handle].ndim; i++)
       if(lo[i]>hi[i]) {
           ga_RegionError(GA[handle].ndim, lo, hi, *g_a);
       }


   gam_Location(ow,handle, lo, &ptr, ld);

   /*
    * return patch address as the distance elements from the reference address
    *
    * .in Fortran we need only the index to the type array: dbl_mb or int_mb
    *  that are elements of COMMON in the the mafdecls.h include file
    * .in C we need both the index and the pointer
    */

   elemsize = (unsigned long)GA[handle].elemsize;

   /* compute index and check if it is correct */
   switch (GA[handle].type){
     case MT_F_DBL:
        *index = (Integer) ((DoublePrecision*)ptr - DBL_MB);
        lref = (unsigned long)DBL_MB;
        break;

     case MT_F_DCPL:
        *index = (Integer) ((DoubleComplex*)ptr - DCPL_MB);
        lref = (unsigned long)DCPL_MB;
        break;

     case MT_F_INT:
        *index = (Integer) ((Integer*)ptr - INT_MB);
        lref = (unsigned long)INT_MB;
        break;

     case MT_F_REAL:
        *index = (Integer) ((float*)ptr - FLT_MB);
        lref = (unsigned long)FLT_MB;
        break;        
   }

#ifdef BYTE_ADDRESSABLE_MEMORY
   /* check the allignment */
   lptr = (unsigned long)ptr;
   if( lptr%elemsize != lref%elemsize ){ 
       printf("%d: lptr=%lu(%lu) lref=%lu(%lu)\n",(int)GAme,lptr,lptr%elemsize,
                                                    lref,lref%elemsize);
       ga_error("nga_access: MA addressing problem: base address misallignment",
                 handle);
   }
#endif

   /* adjust index for Fortran addressing */
   (*index) ++ ;
   FLUSH_CACHE;

   GA_POP_NAME;
}

/*\ PROVIDE ACCESS TO A PATCH OF A GLOBAL ARRAY
\*/
void FATR ga_access_(g_a, ilo, ihi, jlo, jhi, index, ld)
   Integer *g_a, *ilo, *ihi, *jlo, *jhi, *index, *ld;
{
Integer lo[2], hi[2],ndim=ga_ndim_(g_a);

     if(ndim != 2) 
        ga_error("ga_access: 2D API cannot be used for array dimension",ndim);

     lo[0]=*ilo;
     lo[1]=*jlo;
     hi[0]=*ihi;
     hi[1]=*jhi;
     nga_access_(g_a,lo,hi,index,ld);
} 



/*\ RELEASE ACCESS TO A PATCH OF A GLOBAL ARRAY
\*/
void FATR  ga_release_(Integer *g_a, 
                       Integer *ilo, Integer *ihi, Integer *jlo, Integer *jhi)
{}


/*\ RELEASE ACCESS TO A PATCH OF A GLOBAL ARRAY
\*/
void FATR  nga_release_(Integer *g_a, Integer *lo, Integer *hi)
{}


/*\ RELEASE ACCESS & UPDATE A PATCH OF A GLOBAL ARRAY
\*/
void FATR  ga_release_update_(g_a, ilo, ihi, jlo, jhi)
     Integer *g_a, *ilo, *ihi, *jlo, *jhi;
{}


/*\ RELEASE ACCESS & UPDATE A PATCH OF A GLOBAL ARRAY
\*/
void FATR  nga_release_update_(Integer *g_a, Integer *lo, Integer *hi)
{}




void ga_scatter_acc_local(Integer g_a, Void *v,Integer *i,Integer *j,
                          Integer nv, void* alpha, Integer proc) 
{
void **ptr_src, **ptr_dst;
char *ptr_ref;
Integer ldp, item_size, ilo, ihi, jlo, jhi, type;
armci_giov_t desc;
register Integer k, offset;
int rc;

  if (nv < 1) return;

  GA_PUSH_NAME("ga_scatter_local");

  ga_distribution_(&g_a, &proc, &ilo, &ihi, &jlo, &jhi);

  /* get address of the first element owned by proc */
  gaShmemLocation(proc, g_a, ilo, jlo, &ptr_ref, &ldp);

  type = GA[GA_OFFSET + g_a].type;
  item_size = GAsizeofM(type);

  ptr_src = gai_malloc((int)nv*2*sizeof(void*));
  if(ptr_src==NULL)ga_error("gai_malloc failed",nv);
  else ptr_dst=ptr_src+ nv;

  for(k=0; k< nv; k++){
     if(i[k] < ilo || i[k] > ihi  || j[k] < jlo || j[k] > jhi){
       sprintf(err_string,"proc=%d invalid i/j=(%ld,%ld)>< [%ld:%ld,%ld:%ld]",
               (int)proc, i[k], j[k], ilo, ihi, jlo, jhi); 
       ga_error(err_string,g_a);
     }

     offset  = (j[k] - jlo)* ldp + i[k] - ilo;
     ptr_dst[k] = ptr_ref + item_size * offset;
     ptr_src[k] = ((char*)v) + k*item_size;
  }
  desc.bytes = (int)item_size;
  desc.src_ptr_array = ptr_src;
  desc.dst_ptr_array = ptr_dst;
  desc.ptr_array_len = (int)nv;

  if(GA_fence_set)fence_array[proc]=1;

#ifdef PERMUTE_PIDS
    if(GA_Proc_list) proc = GA_inv_Proc_list[proc];
#endif

  if(alpha != NULL) {
    int optype;
    if(type==MT_F_DBL) optype= ARMCI_ACC_DBL;
    else if(type==MT_F_DCPL)optype= ARMCI_ACC_DCP;
    else if(item_size==sizeof(int))optype= ARMCI_ACC_INT;
    else if(item_size==sizeof(long))optype= ARMCI_ACC_LNG;
    else if(type==MT_F_REAL)optype= ARMCI_ACC_FLT;  
    else ga_error("type not supported",type);
    rc= ARMCI_AccV(optype, alpha, &desc, 1, (int)proc);
  }

  if(rc) ga_error("scatter/_acc failed in armci",rc);

  gai_free(ptr_src);

  GA_POP_NAME;
}


/*\ based on subscripts compute pointers
\*/
void gai_sort_proc(Integer* g_a, Integer* sbar, Integer *nv, Integer list[], Integer proc[])
{
int k, ndim;
extern void ga_sort_permutation();

   if (*nv < 1) return;

   ga_check_handleM(g_a, "gai_get_pointers");
   ndim = GA[*g_a+GA_OFFSET].ndim;

   for(k=0; k< *nv; k++)if(!nga_locate_(g_a, sbar+k*ndim, proc+k)){
         gai_print_subscript("invalid subscript",ndim, sbar +k*ndim,"\n");
         ga_error("failed -element:",k);
   }
         
   /* Sort the entries by processor */
   ga_sort_permutation(nv, list, proc);
}
 

/*\ permutes input index list using sort routine used in scatter/gather
\*/
void FATR nga_sort_permut_(Integer* g_a, Integer index[], 
                           Integer* subscr_arr, Integer *nv)
{
    /* The new implementation doesn't change the order of the elements
     * They are identical
     */
    /*
Integer pindex, phandle;

  if (*nv < 1) return;

  if(!MA_push_get(MT_F_INT,*nv, "nga_sort_permut--p", &phandle, &pindex))
              ga_error("MA alloc failed ", *g_a);

  gai_sort_proc(g_a, subscr_arr, nv, index, INT_MB+pindex);
  if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);
    */
}


/*\ SCATTER OPERATION elements of v into the global array
\*/
void FATR  ga_scatter_(Integer *g_a, Void *v, Integer *i, Integer *j,
                       Integer *nv)
{
    register Integer k;
    Integer kk;
    Integer pindex, phandle, item_size;
    Integer proc, type=GA[GA_OFFSET + *g_a].type;

    Integer *aproc, naproc; /* active processes and numbers */
    Integer *map;           /* map the active processes to allocated space */
    char *buf1, *buf2;
    
    Integer *count;   /* counters for each process */
    Integer *nelem;   /* number of elements for each process */
    /* source and destination pointers for each process */
    void ***ptr_src, ***ptr_dst; 
    void **ptr_org; /* the entire pointer array */
    armci_giov_t desc;
    Integer *ilo, *ihi, *jlo, *jhi, *ldp;
    char **ptr_ref;
    
    if (*nv < 1) return;
    
    ga_check_handleM(g_a, "ga_scatter");
    GA_PUSH_NAME("ga_scatter");
    GAstat.numsca++;
    
    if(!MA_push_get(MT_F_INT,*nv, "ga_scatter--p", &phandle, &pindex))
        ga_error("MA alloc failed ", *g_a);

    /* allocate temp memory */
    buf1 = gai_malloc((int) GAnproc *4 * (sizeof(Integer)));
    if(buf1 == NULL) ga_error("gai_malloc failed", 3*GAnproc);
    
    count = (Integer *)buf1;
    nelem = (Integer *)(buf1 + GAnproc * sizeof(Integer));
    aproc = (Integer *)(buf1 + 2 * GAnproc * sizeof(Integer));
    map = (Integer *)(buf1 + 3 * GAnproc * sizeof(Integer));
    
    /* initialize the counters and nelem */
    for(kk=0; kk<GAnproc; kk++) {
        count[kk] = 0; nelem[kk] = 0;
    }
    
    /* find proc that owns the (i,j) element; store it in temp: INT_MB[] */
    for(k=0; k< *nv; k++) {
        if(! ga_locate_(g_a, i+k, j+k, INT_MB+pindex+k)){
            sprintf(err_string,"invalid i/j=(%ld,%ld)", i[k], j[k]);
            ga_error(err_string,*g_a);
        }
        nelem[INT_MB[pindex+k]]++;
    }

    naproc = 0;
    for(k=0; k<GAnproc; k++) if(nelem[k] > 0) {
        aproc[naproc] = k;
        map[k] = naproc;
        naproc ++;
    }
    
    buf2 = gai_malloc((int)(2*naproc*sizeof(void **) + 2*(*nv)*sizeof(void *) +
                      5*naproc*sizeof(Integer) + naproc*sizeof(char*)));
    if(buf2 == NULL) ga_error("gai_malloc failed", naproc);
 
    ptr_src = (void ***)buf2;
    ptr_dst = (void ***)(buf2 + naproc*sizeof(void **));
    ptr_org = (void **)(buf2 + 2*naproc*sizeof(void **));
    ptr_ref = (char **)(buf2+2*naproc*sizeof(void **)+2*(*nv)*sizeof(void *));
    ilo = (Integer *)(((char*)ptr_ref) + naproc*sizeof(char*));
    ihi = ilo + naproc;
    jlo = ihi + naproc;
    jhi = jlo + naproc;
    ldp = jhi + naproc;

    for(kk=0; kk<naproc; kk++) {
        ga_distribution_(g_a, &aproc[kk],
                         &(ilo[kk]), &(ihi[kk]), &(jlo[kk]), &(jhi[kk]));
        
        /* get address of the first element owned by proc */
        gaShmemLocation(aproc[kk], *g_a, ilo[kk], jlo[kk], &(ptr_ref[kk]),
                        &(ldp[kk]));
    }
    
    /* determine limit for message size --  v,i, & j will travel together */
    item_size = GAsizeofM(type);
    GAbytes.scatot += (double)item_size**nv ;
    GAbytes.scaloc += (double)item_size* nelem[INT_MB[pindex+GAme]];

    ptr_src[0] = ptr_org; ptr_dst[0] = ptr_org + (*nv);
    for(k=1; k<naproc; k++) {
        ptr_src[k] = ptr_src[k-1] + nelem[aproc[k-1]];
        ptr_dst[k] = ptr_dst[k-1] + nelem[aproc[k-1]];
    }
    
    for(k=0; k<(*nv); k++){
        Integer this_count;
        proc = INT_MB[pindex+k]; this_count = count[proc]; count[proc]++;
        proc = map[proc];
        ptr_src[proc][this_count] = ((char*)v) + k * item_size;
        if(i[k] < ilo[proc] || i[k] > ihi[proc]  ||
           j[k] < jlo[proc] || j[k] > jhi[proc]){
          sprintf(err_string,"proc=%d invalid i/j=(%ld,%ld)><[%ld:%ld,%ld:%ld]",
             (int)proc, i[k], j[k], ilo[proc], ihi[proc], jlo[proc], jhi[proc]);
            ga_error(err_string, *g_a);
        }
        ptr_dst[proc][this_count] = ptr_ref[proc] + item_size *
            ((j[k] - jlo[proc])* ldp[proc] + i[k] - ilo[proc]);
    }
    
    /* source and destination pointers are ready for all processes */
    for(k=0; k<naproc; k++) {
        int rc;

        desc.bytes = (int)item_size;
        desc.src_ptr_array = ptr_src[k];
        desc.dst_ptr_array = ptr_dst[k];
        desc.ptr_array_len = (int)nelem[aproc[k]];
        
        rc = ARMCI_PutV(&desc, 1, (int)aproc[k]);
        if(rc) ga_error("scatter failed in armci",rc);
    }

    gai_free(buf2);
    gai_free(buf1);

    if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);
    GA_POP_NAME;
}
      


/*\ SCATTER OPERATION elements of v into the global array
\*/
void FATR  ga_scatter_acc_(g_a, v, i, j, nv, alpha)
     Integer *g_a, *nv, *i, *j;
     Void *v, *alpha;
{
register Integer k;
Integer pindex, phandle, item_size;
Integer first, nelem, proc, type=GA[GA_OFFSET + *g_a].type;

  if (*nv < 1) return;

  ga_check_handleM(g_a, "ga_scatter_acc");
  GA_PUSH_NAME("ga_scatter_acc");
  GAstat.numsca++;

  if(!MA_push_get(MT_F_INT,*nv, "ga_scatter_acc--p", &phandle, &pindex))
            ga_error("MA alloc failed ", *g_a);

  /* find proc that owns the (i,j) element; store it in temp: INT_MB[] */
  for(k=0; k< *nv; k++) if(! ga_locate_(g_a, i+k, j+k, INT_MB+pindex+k)){
         sprintf(err_string,"invalid i/j=(%ld,%ld)", i[k], j[k]);
         ga_error(err_string,*g_a);
  }

  /* determine limit for message size --  v,i, & j will travel together */
  item_size = GAsizeofM(type);
  GAbytes.scatot += (double)item_size**nv ;

  /* Sort the entries by processor */
  ga_sort_scat(nv, v, i, j, INT_MB+pindex, type );

  /* go through the list again executing scatter for each processor */

  first = 0;
  do {
      proc  = INT_MB[pindex+first];
      nelem = 0;

      /* count entries for proc from "first" to last */
      for(k=first; k< *nv; k++){
        if(proc == INT_MB[pindex+k]) nelem++;
        else break;
      }

      if(proc == GAme){
             GAbytes.scaloc += (double)item_size* nelem ;
      }

      ga_scatter_acc_local(*g_a, ((char*)v)+item_size*first, i+first,
                           j+first, nelem, alpha, proc);
      first += nelem;

  }while (first< *nv);

  if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);

  GA_POP_NAME;
}



/*\ permutes input index list using sort routine used in scatter/gather
\*/
void FATR  ga_sort_permut_(g_a, index, i, j, nv)
     Integer *g_a, *nv, *i, *j, *index;
{
    /* The new implementation doesn't change the order of the elements
     * They are identical
     */

#if 0
register Integer k;
Integer pindex, phandle;
extern void ga_sort_permutation();

  if (*nv < 1) return;

  if(!MA_push_get(MT_F_INT,*nv, "ga_sort_permut--p", &phandle, &pindex))
            ga_error("MA alloc failed ", *g_a);

  /* find proc that owns the (i,j) element; store it in temp: INT_MB[] */
  for(k=0; k< *nv; k++) if(! ga_locate_(g_a, i+k, j+k, INT_MB+pindex+k)){
         sprintf(err_string,"invalid i/j=(%ld,%ld)", i[k], j[k]);
         ga_error(err_string,*g_a);
  }

  /* Sort the entries by processor */
  ga_sort_permutation(nv, index, INT_MB+pindex);
  if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);
#endif
}




#define SCATTER -99
#define GATHER -98
#define SCATTER_ACC -97

/*\ GATHER OPERATION elements from the global array into v
\*/
void gai_gatscat(int op, Integer* g_a, void* v, Integer subscript[], 
                 Integer* nv, double *locbytes, double* totbytes, void *alpha)
{
    Integer k, handle=*g_a+GA_OFFSET;
    int  ndim, item_size, type;
    Integer *proc, phandle;

    Integer *aproc, naproc; /* active processes and numbers */
    Integer *map;           /* map the active processes to allocated space */
    char *buf1, *buf2;
    
    Integer *count;        /* counters for each process */
    Integer *nelem;        /* number of elements for each process */
    /* source and destination pointers for each process */
    void ***ptr_src, ***ptr_dst; 
    void **ptr_org; /* the entire pointer array */
    armci_giov_t desc;
    
    GA_PUSH_NAME("gai_gatscat");

    if(!MA_push_stack(MT_F_INT,*nv,"ga_gat-p",&phandle)) 
        ga_error("MAfailed",*g_a);
    if(!MA_get_pointer(phandle, &proc)) ga_error("MA pointer failed ", *g_a);

    ndim = GA[handle].ndim;
    type = GA[handle].type;
    item_size = GA[handle].elemsize;
    *totbytes += (double)item_size**nv;

    /* allocate temp memory */
    buf1 = gai_malloc((int) GAnproc * 4 * (sizeof(Integer)));
    if(buf1 == NULL) ga_error("gai_malloc failed", 3*GAnproc);
    
    count = (Integer *)buf1;
    nelem = (Integer *)(buf1 + GAnproc * sizeof(Integer));
    aproc = (Integer *)(buf1 + 2 * GAnproc * sizeof(Integer));
    map = (Integer *)(buf1 + 3 * GAnproc * sizeof(Integer));
    
    /* initialize the counters and nelem */
    for(k=0; k<GAnproc; k++) count[k] = 0; 
    for(k=0; k<GAnproc; k++) nelem[k] = 0;

    /* get the process id that the element should go and count the
     * number of elements for each process
     */
    for(k=0; k<*nv; k++) {
        if(!nga_locate_(g_a, subscript+k*ndim, proc+k)) {
            gai_print_subscript("invalid subscript",ndim, subscript+k*ndim,"\n");
            ga_error("failed -element:",k);
        }
        nelem[proc[k]]++;
    }

    /* find the active processes (with which transfer data) */
    naproc = 0;
    for(k=0; k<GAnproc; k++) if(nelem[k] > 0) {
        aproc[naproc] = k;
        map[k] = naproc;
        naproc ++;
    }

    buf2 = gai_malloc((int)(2*naproc*sizeof(void **) + 2*(*nv)*sizeof(void *)));
    if(buf2 == NULL) ga_error("gai_malloc failed", 2*naproc);
    
    ptr_src = (void ***)buf2;
    ptr_dst = (void ***)(buf2 + naproc * sizeof(void **));
    ptr_org = (void **)(buf2 + 2 * naproc * sizeof(void **));
    
    /* set the pointers as
     *    P0            P1                  P0          P1        
     * ptr_src[0]   ptr_src[1] ...       ptr_dst[0]  ptr_dst[1] ...
     *        \          \                    \          \
     * ptr_org |-------------------------------|---------------------------|
     *         |              (*nv)            |            (*nv)          |
     *         | nelem[0] | nelem[1] |...      | nelem[0] | nelem[1] |...
     */
    ptr_src[0] = ptr_org; ptr_dst[0] = ptr_org + (*nv);
    for(k=1; k<naproc; k++) {
        ptr_src[k] = ptr_src[k-1] + nelem[aproc[k-1]];
        ptr_dst[k] = ptr_dst[k-1] + nelem[aproc[k-1]];
    }

    *locbytes += (double)item_size* nelem[GAme];
    
/*
#ifdef PERMUTE_PIDS
    if(GA_Proc_list) p = GA_inv_Proc_list[p];
#endif
*/    
    switch(op) { 
      case GATHER:
        /* go through all the elements
         * for process 0: ptr_src[0][0, 1, ...] = subscript + offset0...
         *                ptr_dst[0][0, 1, ...] = v + offset0...
         * for process 1: ptr_src[1][...] ...
         *                ptr_dst[1][...] ...
         */  
        for(k=0; k<(*nv); k++){
            ptr_dst[map[proc[k]]][count[proc[k]]] = ((char*)v) + k * item_size;
            gam_Loc_ptr(proc[k], handle,  (subscript+k*ndim),
                        ptr_src[map[proc[k]]]+count[proc[k]]);
            count[proc[k]]++;
        }
        
        /* source and destination pointers are ready for all processes */
        for(k=0; k<naproc; k++) {
            int rc;

            desc.bytes = (int)item_size;
            desc.src_ptr_array = ptr_src[k];
            desc.dst_ptr_array = ptr_dst[k];
            desc.ptr_array_len = (int)nelem[aproc[k]];
            
            rc=ARMCI_GetV(&desc, 1, (int)aproc[k]);
            if(rc) ga_error("gather failed in armci",rc);
        }
        break;
      case SCATTER:
        /* go through all the elements
         * for process 0: ptr_src[0][0, 1, ...] = v + offset0...
         *                ptr_dst[0][0, 1, ...] = subscript + offset0...
         * for process 1: ptr_src[1][...] ...
         *                ptr_dst[1][...] ...
         */
        for(k=0; k<(*nv); k++){
            ptr_src[map[proc[k]]][count[proc[k]]] = ((char*)v) + k * item_size;
            gam_Loc_ptr(proc[k], handle,  (subscript+k*ndim),
                        ptr_dst[map[proc[k]]]+count[proc[k]]);
            count[proc[k]]++;
        }

        /* source and destination pointers are ready for all processes */
        for(k=0; k<naproc; k++) {
            int rc;

            desc.bytes = (int)item_size;
            desc.src_ptr_array = ptr_src[k];
            desc.dst_ptr_array = ptr_dst[k];
            desc.ptr_array_len = (int)nelem[aproc[k]];
            
            if(GA_fence_set) fence_array[aproc[k]]=1;
            
            rc=ARMCI_PutV(&desc, 1, (int)aproc[k]);
            if(rc) ga_error("scatter failed in armci",rc);
        }
        break;
      case SCATTER_ACC:
        /* go through all the elements
         * for process 0: ptr_src[0][0, 1, ...] = v + offset0...
         *                ptr_dst[0][0, 1, ...] = subscript + offset0...
         * for process 1: ptr_src[1][...] ...
         *                ptr_dst[1][...] ...
         */
        for(k=0; k<(*nv); k++){
            ptr_src[map[proc[k]]][count[proc[k]]] = ((char*)v) + k * item_size;
            gam_Loc_ptr(proc[k], handle,  (subscript+k*ndim),
                        ptr_dst[map[proc[k]]]+count[proc[k]]);
            count[proc[k]]++;
        }

        /* source and destination pointers are ready for all processes */
        for(k=0; k<naproc; k++) {
            int rc;
            
            desc.bytes = (int)item_size;
            desc.src_ptr_array = ptr_src[k];
            desc.dst_ptr_array = ptr_dst[k];
            desc.ptr_array_len = (int)nelem[aproc[k]];
            
            if(GA_fence_set) fence_array[aproc[k]]=1;
            
            if(alpha != NULL) {
                int optype;
                if(type==MT_F_DBL) optype= ARMCI_ACC_DBL;
                else if(type==MT_F_DCPL)optype= ARMCI_ACC_DCP;
                else if(item_size==sizeof(int))optype= ARMCI_ACC_INT;
                else if(item_size==sizeof(long))optype= ARMCI_ACC_LNG;
                else if(type==MT_F_REAL)optype= ARMCI_ACC_FLT; 
                else ga_error("type not supported",type);
                rc= ARMCI_AccV(optype, alpha, &desc, 1, (int)aproc[k]);
            }
            if(rc) ga_error("scatter_acc failed in armci",rc);
        }
        break;        
      default: ga_error("operation not supported",op);
    }

    gai_free(buf2); gai_free(buf1);
    
    if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);
    GA_POP_NAME;
}



/*\ GATHER OPERATION elements from the global array into v
\*/
void FATR nga_gather_(Integer *g_a, void* v, Integer subscript[], Integer *nv)
{

  if (*nv < 1) return;
  ga_check_handleM(g_a, "nga_gather");
  GA_PUSH_NAME("nga_gather");
  GAstat.numgat++;

  gai_gatscat(GATHER,g_a,v,subscript,nv,&GAbytes.gattot,&GAbytes.gatloc, NULL);

  GA_POP_NAME;
}


void FATR nga_scatter_(Integer *g_a, void* v, Integer subscript[], Integer *nv)
{

  if (*nv < 1) return;
  ga_check_handleM(g_a, "nga_scatter");
  GA_PUSH_NAME("nga_scatter");
  GAstat.numsca++;

  gai_gatscat(SCATTER,g_a,v,subscript,nv,&GAbytes.scatot,&GAbytes.scaloc, NULL);

  GA_POP_NAME;
}

void FATR nga_scatter_acc_(Integer *g_a, void* v, Integer subscript[],
                           Integer *nv, void *alpha)
{

  if (*nv < 1) return;
  ga_check_handleM(g_a, "nga_scatter_acc");
  GA_PUSH_NAME("nga_scatter_acc");
  GAstat.numsca++;

  gai_gatscat(SCATTER_ACC, g_a, v, subscript, nv, &GAbytes.scatot,
              &GAbytes.scaloc, alpha);

  GA_POP_NAME;
}

void FATR  ga_gather000_(g_a, v, i, j, nv)
     Integer *g_a, *nv, *i, *j;
     Void *v;
{
int k;
Integer *sbar = (Integer*)malloc(2*sizeof(Integer)*  (int)*nv);
     if(!sbar) ga_error("gather:malloc failed",*nv);
     for(k=0;k<*nv;k++){
          sbar[2*k] = i[k];
          sbar[2*k+1] = j[k];
     }
     nga_gather_(g_a,v,sbar,nv);
     free(sbar);
}
  


/*\ SCATTER OPERATION elements of v into the global array
\*/
void FATR  ga_scatter000_(g_a, v, i, j, nv)
     Integer *g_a, *nv, *i, *j;
     Void *v;
{
int k;
Integer *sbar = (Integer*)malloc(2*sizeof(Integer)* (int) *nv);
     if(!sbar) ga_error("scatter:malloc failed",*nv);
     for(k=0;k<*nv;k++){
          sbar[2*k] = i[k];
          sbar[2*k+1] = j[k];
     }
     nga_scatter_(g_a,v,sbar,nv);
     free(sbar);
}


/*\ GATHER OPERATION elements from the global array into v
\*/
void FATR  ga_gather_(Integer *g_a, void *v, Integer *i, Integer *j,
                      Integer *nv)
{
    register Integer k;
    Integer kk;
    Integer pindex, phandle, item_size;
    Integer proc;

    Integer *aproc, naproc; /* active processes and numbers */
    Integer *map;           /* map the active processes to allocated space */
    char *buf1, *buf2;
    
    Integer *count;   /* counters for each process */
    Integer *nelem;   /* number of elements for each process */
    /* source and destination pointers for each process */
    void ***ptr_src, ***ptr_dst; 
    void **ptr_org; /* the entire pointer array */
    armci_giov_t desc;
    Integer *ilo, *ihi, *jlo, *jhi, *ldp;
    char **ptr_ref;
    
    if (*nv < 1) return;

    ga_check_handleM(g_a, "ga_gather");
    GA_PUSH_NAME("ga_gather");
    GAstat.numgat++;

    if(!MA_push_get(MT_F_INT, *nv, "ga_gather--p", &phandle, &pindex))
        ga_error("MA failed ", *g_a);

    /* allocate temp memory */
    buf1 = gai_malloc((int)GAnproc *4 *  (sizeof(Integer)));
    if(buf1 == NULL) ga_error("gai_malloc failed", 3*GAnproc);
    
    count = (Integer *)buf1;
    nelem = (Integer *)(buf1 + GAnproc * sizeof(Integer));
    aproc = (Integer *)(buf1 + 2 * GAnproc * sizeof(Integer));
    map = (Integer *)(buf1 + 3 * GAnproc * sizeof(Integer));
   
    /* initialize the counters and nelem */
    for(kk=0; kk<GAnproc; kk++) {
        count[kk] = 0; nelem[kk] = 0;
    }
    
    /* find proc that owns the (i,j) element; store it in temp: INT_MB[] */
    for(k=0; k< *nv; k++) {
        if(! ga_locate_(g_a, i+k, j+k, INT_MB+pindex+k)){
            sprintf(err_string,"invalid i/j=(%ld,%ld)", i[k], j[k]);
            ga_error(err_string, *g_a);
        }
        nelem[INT_MB[pindex+k]]++;
    }

    naproc = 0;
    for(k=0; k<GAnproc; k++) if(nelem[k] > 0) {
        aproc[naproc] = k;
        map[k] = naproc;
        naproc ++;
    }
    
    buf2 = gai_malloc((int)(2*naproc*sizeof(void **) + 2*(*nv)*sizeof(void *) +
                      5*naproc*sizeof(Integer) + naproc*sizeof(char*)));
    if(buf2 == NULL) ga_error("gai_malloc failed", naproc);
 
    ptr_src = (void ***)buf2;
    ptr_dst = (void ***)(buf2 + naproc*sizeof(void **));
    ptr_org = (void **)(buf2 + 2*naproc*sizeof(void **));
    ptr_ref = (char **)(buf2+2*naproc*sizeof(void **)+2*(*nv)*sizeof(void *));
    ilo = (Integer *)(((char*)ptr_ref) + naproc*sizeof(char*));
    ihi = ilo + naproc;
    jlo = ihi + naproc;
    jhi = jlo + naproc;
    ldp = jhi + naproc;

    for(kk=0; kk<naproc; kk++) {
        ga_distribution_(g_a, &aproc[kk],
                         &(ilo[kk]), &(ihi[kk]), &(jlo[kk]), &(jhi[kk]));
        
        /* get address of the first element owned by proc */
        gaShmemLocation(aproc[kk], *g_a, ilo[kk], jlo[kk], &(ptr_ref[kk]),
                        &(ldp[kk]));
    }
    
    item_size = GA[GA_OFFSET + *g_a].elemsize;
    GAbytes.gattot += (double)item_size**nv;
    GAbytes.gatloc += (double)item_size * nelem[INT_MB[pindex+GAme]];

    ptr_src[0] = ptr_org; ptr_dst[0] = ptr_org + (*nv);
    for(k=1; k<naproc; k++) {
        ptr_src[k] = ptr_src[k-1] + nelem[aproc[k-1]];
        ptr_dst[k] = ptr_dst[k-1] + nelem[aproc[k-1]];
    }
    
    for(k=0; k<(*nv); k++){
        Integer this_count;
        proc = INT_MB[pindex+k]; 
        this_count = count[proc]; 
        count[proc]++;
        proc = map[proc]; 
        ptr_dst[proc][this_count] = ((char*)v) + k * item_size;

        if(i[k] < ilo[proc] || i[k] > ihi[proc]  ||
           j[k] < jlo[proc] || j[k] > jhi[proc]){
          sprintf(err_string,"proc=%d invalid i/j=(%ld,%ld)><[%ld:%ld,%ld:%ld]",
                 (int)proc,i[k],j[k],ilo[proc],ihi[proc],jlo[proc], jhi[proc]);
            ga_error(err_string, *g_a);
        }
        ptr_src[proc][this_count] = ptr_ref[proc] + item_size *
            ((j[k] - jlo[proc])* ldp[proc] + i[k] - ilo[proc]);
    }
    
    /* source and destination pointers are ready for all processes */
    for(k=0; k<naproc; k++) {
        int rc;

        desc.bytes = (int)item_size;
        desc.src_ptr_array = ptr_src[k];
        desc.dst_ptr_array = ptr_dst[k];
        desc.ptr_array_len = (int)nelem[aproc[k]];
        
        rc=ARMCI_GetV(&desc, 1, (int)aproc[k]);
        if(rc) ga_error("gather failed in armci",rc);
    }

    gai_free(buf2);
    gai_free(buf1);

    if(! MA_pop_stack(phandle)) ga_error(" pop stack failed!",phandle);
    GA_POP_NAME;
}
      
           



/*\ READ AND INCREMENT AN ELEMENT OF A GLOBAL ARRAY
\*/
Integer FATR nga_read_inc_(Integer* g_a, Integer* subscript, Integer* inc)
{
Integer *ptr, ldp[MAXDIM], value, proc, handle=GA_OFFSET+*g_a;
int optype;

    ga_check_handleM(g_a, "nga_read_inc");
    GA_PUSH_NAME("ga_read_inc");

    if(GA[handle].type!=MT_F_INT) ga_error("type must be integer",*g_a);

    GAstat.numrdi++;
    GAbytes.rditot += (double)sizeof(Integer);

    /* find out who owns it */
    nga_locate_(g_a, subscript, &proc);

    /* get an address of the g_a(subscript) element */
    gam_Location(proc, handle,  subscript, (char**)&ptr, ldp);

#   ifdef EXT_INT
      optype = ARMCI_FETCH_AND_ADD_LONG;
#   else
      optype = ARMCI_FETCH_AND_ADD;
#   endif

    if(GAme == proc)GAbytes.rdiloc += (double)sizeof(Integer);

#ifdef PERMUTE_PIDS
    if(GA_Proc_list) proc = GA_inv_Proc_list[proc];
#endif

    ARMCI_Rmw(optype, (int*)&value, (int*)ptr, (int)*inc, (int)proc);

   GA_POP_NAME;
   return(value);
}




/*\ READ AND INCREMENT AN ELEMENT OF A GLOBAL ARRAY
\*/
Integer FATR ga_read_inc_(g_a, i, j, inc)
        Integer *g_a, *i, *j, *inc;
{
Integer  value, subscript[2];

#ifdef GA_TRACE
       trace_stime_();
#endif

   subscript[0] =*i;
   subscript[1] =*j;
   value = nga_read_inc_(g_a, subscript, inc);

#  ifdef GA_TRACE
     trace_etime_();
     op_code = GA_OP_RDI;
     trace_genrec_(g_a, i, i, j, j, &op_code);
#  endif

   return(value);
}
