#
# NT Makefile for a portable dynamic memory allocator.

OBJDIR=.\obj
OBJ_OPTIMIZE = $(OBJDIR)\f2c.obj         \
               $(OBJDIR)\ma.obj          \
               $(OBJDIR)\maf.obj         \
               $(OBJDIR)\table.obj

OBJ          = $(OBJDIR)\string-util.obj \
               $(OBJDIR)\error.obj

HEADERS      = macommon.h      \
               matypes.h       \
               macdecls.h      \
               mafdecls.fh \
               typesf2c.h \
               winf2c.h \
               winutil.h


LOC_DEFINES = -DVERIFY -DSTATS
# -D_CONSOLE
LOC_INCLUDES = -I..\include
INCDIR = ..\include

LIBRARY = ma.lib
LIB_DISTRIB = ..\lib\win32

!INCLUDE ..\config\NTmakefile.h
!INCLUDE ..\config\NTmakelib.h


testf.exe: .\obj\testf.obj $(LIBRARY_PATH)
	$(FC) $(FOPT) /Fetestf.exe $**

testc.exe: .\obj\testc.obj $(LIBRARY_PATH)
	$(CC) $(COPT) /Fetestc.exe $**

test-coalesce.exe: .\obj\test-coalesce.obj $(LIBRARY_PATH)
	$(CC) $(COPT) /Fetest-coalesce.exe $**
