#include<stdio.h>
#include<stdlib.h>

#include"mpi.h"
#include"ga.h"
#include"macdecls.h"

int main(int argv, char **argc)
{
  int g_A, local_A[5][5], local_B[5][5], value = 3;
  int rank, size, i, j, ld = 5;
  int dims[2]={10,10}, lo[2]={0,0}, hi[2]={4,4}, lo2[2]={2,2}, hi2[2]={6,6};
  int a=5, b=3, c=4;

  MPI_Init(&argv, &argc);
  MA_init(C_INT, 1000, 1000);
  GA_Initialize();

  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  g_A=NGA_Create(C_INT, 2, dims, "array_A", NULL);

  /*Using collective operators like _FILL _PRINT _ZERO to check the process*/

  GA_Fill(g_A, &value);
  GA_Print(g_A);

  /*creating local array to pass value that generated by one process to other   process to manipulate*/ 
  /*GA_Put and _Get are one-sided operators*/
 
  if(rank==0) 
    {
      for(i=0; i<5; i++)
	{
	for(j=0; j<5; j++)
	  local_A[i][j]=rand()%10;
	}
      NGA_Put(g_A, lo, hi, local_A, &ld);
      
      for(i=0; i<5; i++)
	{
	for(j=0; j<5; j++)
	  printf("%d ", local_A[i][j]);
        printf("\n\n");
	}
      printf("\n Rank : %d\n", rank);
      printf("%d - %d\n", rank, a=a+b+c);
    }
  
  /*  if(rank==2)
    {
      for(i=0; i<5; i++)
	{
	  for(j=0; j<5; j++)
	    printf("%d ", local_A[i][j]);
	  printf("\n");
	}
      printf("\n Rank : %d\n", rank);
      printf("%d - %d\n", rank, a+c);
      }*/
  
  GA_Sync();/*_Sync is like barrier program waits until all process reaches this point and put, acc, etc "data" is visible to all proceses */ 
  GA_Print(g_A);
  
  if(rank==1)
    {
      NGA_Get(g_A, lo2, hi2, local_B, &ld);
      
      for(j=0; j<5; j++)
	{
        for(i=0; i<5; i++)
	  printf("%d ", local_B[i][j]);
        printf("\n");
	}
      printf("\n Rank : %d\n", rank);
      printf("%d - %d\n", rank, a+b);
    }

  /*print value is transformed -- reason to find*/
  GA_Destroy(g_A);
  
  GA_Terminate();
  MPI_Finalize();

  return 0;
}


