#$Id: makefile,v 1.2 1996-07-17 15:59:15 mogill Exp $
#
# ChemIO makefile for making ELIO
#
#   Written by Jace A Mogill
#              12 June 1996
#	       Argonne National Laboratory
#
#

OBJ = elio.o
LIBRARY = libelio.a
HEADERS = elio.h chemio.h


include ../../config/makefile.h
include ../../config/makelib.h

$(OBJ) : $(HEADERS)

