extern int iw_BlockingReadFromSocket(int, char *, long);
extern int iw_BlockingWriteToSocket(int, char *, long);
extern int iw_NonBlockingReadFromSocket(int, char *, long);
extern int iw_NonBlockingWriteToSocket(int, char *, long);
extern void iw_CreateSocketAndBind();
extern int iw_ListenAndAccept();
extern int iw_CreateSocketAndConnect();
extern long iw_PollSocket(int);
extern long iw_WriteableSocket(int);
extern int iw_RemoteCreate();
extern void iw_Error();
extern double iw_Dclock();
