# NT makefile

OBJDIR=.\obj

OBJ = $(OBJDIR)\disk.arrays.obj \
   $(OBJDIR)\disk.param.obj \
   $(OBJDIR)\patch.util.obj \
   $(OBJDIR)\env.obj \
   $(OBJDIR)\fortran.obj

HEADERS      = dra.h dra.fh
TESTUTIL =  $(OBJDIR)\ffflush.obj

LOC_INCLUDES = -I..\..\include
INCDIR = ..\..\include

LIBRARY = dra.lib
LIB_DISTRIB = ..\..\lib\win32

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h

LIBS = /MT $(LIB_DISTRIB)\pario.lib\
 $(LIB_DISTRIB)\global.lib  $(LIB_DISTRIB)\tcgmsg-mpi.lib\
 $(LIB_DISTRIB)\ma.lib  $(LIB_DISTRIB)\linalg.lib\
 $(LIB_DISTRIB)\armci.lib $(MPI) wsock32.lib

#test.exe: $(OBJDIR)\test.obj  $(OBJDIR)\ffflush.obj
#        $(FC) $(FOPT) /Fetest.exe $** $(LIBS)
