#
# Makefile for the Argonne Portable Microsecond Clock and logging packages
#
# Written by:  Arun Nanda  (07/17/91)
#
# USAGE:
#    To create the USC library for machine class 'mc_class', type
#                make MACHINE=mc_class
#    To clean the directory to its original contents, type
#                make clean
#

RM     = /bin/rm
AR     = ar ruv
RANLIB = ranlib
CC     = cc

DEBUG  = -g

# Machines with library archiver/randomizer as defined above

GOODONES = SUN NEXT BALANCE SYMMETRY MULTIMAX BFLY1 BFLY2 BFLY2_TCMP ALLIANT

.c.o:	$*.c
	$(CC) $(CFLAGS) $(DEBUG) -c -D$(MACHINE) $*.c 

.SUFFIXES:  .o .c

USC_HDR = usc_main.h usc.h
USC_SRC = usc.c
USC_OBJ = usc.o
ALOG_HDR = alog.h
ALOG_SRC = alog.c alogf.c
ALOG_OBJ = alog.o alogf.o

all:
	@if [ -z "$(MACHINE)" ] ; \
	then \
		echo 'USAGE: make MACHINE=<machine_class>' ; \
	else \
		echo Making ALOG for machine $(MACHINE) ; \
		make MACHINE=$(MACHINE) $(MACHINE) ; \
	fi

$(USC_OBJ):  $(USC_SRC) $(USC_HDR)

$(ALOG_OBJ):  $(ALOG_SRC) $(ALOG_HDR)

libalog.a:  $(ALOG_OBJ) $(USC_OBJ)
	$(AR) $@ $?
	$(RANLIB) $@

mergelogs: eventdefs.h mergelogs.o
	$(CC) -o mergelogs mergelogs.o

clean:
	$(RM) -f *~ *.o tags TAGS core libalog.a mergelogs
	@cd usctest; make clean

# Define machine-dependent targets below if the library archiver or
# randomizer on that machine is  different from those defined here

$(GOODONES):
	@make MACHINE=$(MACHINE) mergelogs

ATT_3B2 IBM_RS6000 TITAN IPSC860_HOST SGI:
	@make MACHINE=$(MACHINE) RANLIB=true libalog.a mergelogs

IPSC860_NODE:
	@make MACHINE=$(MACHINE) AR="ar860 r" RANLIB=true CFLAGS="-node" libalog.a mergelogs

DELTA IPSC860_NODE_PGI:
	@make MACHINE=$(MACHINE) AR="ar860 r" RANLIB=true CC=icc CFLAGS="-node" libalog.a

CAP2_CELL:
	@make MACHINE=$(MACHINE) CC="cc.cc7" CFLAGS="-I/usr/cap/sys.c7/include" libalog.a

CAP2_HOST:
	make MACHINE=$(MACHINE) CC="cc.hc7" CFLAGS="-I/usr/cap/sys.c7/include" libalog.a
