SUBDIRS = .\elio .\dra .\eaf .\sf

!include ..\config\NTmakefile.h
LIBDIR = ..\lib\win32
COMPLIBS = elio.lib eaf.lib dra.lib sf.lib

all: $(SUBDIRS)
	!cd $** & nmake -nologo
	cd $(LIBDIR)
	$(AR) /out:pario.lib $(COMPLIBS)  
	-del $(COMPLIBS)
	
	
clean: $(SUBDIRS)
	!cd $** & nmake -nologo clean
	-@erase /q $(LIBDIR)\pario.lib
