#$Id: makefile,v 1.5 1997-02-17 20:51:32 d3g681 Exp $

# Initial version by Jace A Mogill (12 June 1996) ANL

LIBRARY = libchemio.a
SUBDIRS = elio eaf dra sf

include ../config/makefile.h
include ../config/makelib.h

