all: simple hashtable

.PHONY : simple
simple:
	@echo '>>> Making simple only <<<'
	(cd simple;make)

.PHONY : hashtable
hashtable:
	@echo '>>> Making hashtable only <<<'
	(cd hashtable;make)

clean:
	(cd simple;make clean)
	(cd hashtable;make clean)
