if (INPUT)
  if (OUTPUT)
    message(STATUS "Reading ${INPUT} ...")
    file(READ "${INPUT}" in0)
    string(REGEX REPLACE "\r?\n" ";" lines "${in0}")
    set(out "")
    foreach (l ${lines})
      # remove comments
      string(REGEX REPLACE "/\\*..*\\*/" "" l "${l}")
      # ignore lines with leading whitespace
      string(REGEX MATCH "^  *" found "${l}")
      if (found) 
        set(l "")
      endif ()
      if (l)
        set(out "${out}${l}\n")
      endif (l)
    endforeach ()
    message(STATUS "Writing ${OUTPUT} ...")
    file(WRITE "${OUTPUT}" "${out}")
  else (OUTPUT)
    message(ERROR "OUTPUT variable must be set")
  endif (OUTPUT)
else (INPUT)
  message(ERROR "INPUT variable must be set")
endif (INPUT)
