# CMake generated Testfile for 
# Source directory: /home/d3g293/ga-oshmem/global/testing
# Build directory: /home/d3g293/ga-oshmem/build_shmem/global/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(mulmatpatchc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "1" "/home/d3g293/ga-oshmem/build_shmem/global/testing/mulmatpatchc.x")
set_tests_properties(mulmatpatchc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;59;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(elempatch "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/elempatch.x")
set_tests_properties(elempatch PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;62;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(getmem "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/getmem.x")
set_tests_properties(getmem PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;63;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(mtest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/mtest.x")
set_tests_properties(mtest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;64;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(normc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/normc.x")
set_tests_properties(normc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;65;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(matrixc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/matrixc.x")
set_tests_properties(matrixc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;66;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ntestc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ntestc.x")
set_tests_properties(ntestc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;67;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nbtestc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nbtestc.x")
set_tests_properties(nbtestc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;68;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ntestfc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ntestfc.x")
set_tests_properties(ntestfc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;69;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(packc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/packc.x")
set_tests_properties(packc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;70;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(print "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/print.x")
set_tests_properties(print PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;71;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(scan_addc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/scan_addc.x")
set_tests_properties(scan_addc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;72;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(scan_copyc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/scan_copyc.x")
set_tests_properties(scan_copyc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;73;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testc.x")
set_tests_properties(testc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;74;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testmult "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testmult.x")
set_tests_properties(testmult PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;75;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testmatmultc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testmatmultc.x")
set_tests_properties(testmatmultc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;76;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testmultrect "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testmultrect.x")
set_tests_properties(testmultrect PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;77;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(gemmtest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/gemmtest.x")
set_tests_properties(gemmtest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;78;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(read_only "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/read_only.x")
set_tests_properties(read_only PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;79;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(cache_test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/cache_test.x")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;80;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(unpackc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/unpackc.x")
set_tests_properties(unpackc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;81;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(perf2 "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/perf2.x")
set_tests_properties(perf2 PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;82;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ga-mpi "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ga-mpi.x")
set_tests_properties(ga-mpi PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;83;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(lock "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/lock.x")
set_tests_properties(lock PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;84;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(comm_init "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/comm_init.x")
set_tests_properties(comm_init PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;85;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(patch_enumc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/patch_enumc.x")
set_tests_properties(patch_enumc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;87;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(simple_groups_commc "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/simple_groups_commc.x")
set_tests_properties(simple_groups_commc PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;88;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(thread_perf_contig "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/thread_perf_contig.x")
set_tests_properties(thread_perf_contig PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;89;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(thread_perf_strided "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/thread_perf_strided.x")
set_tests_properties(thread_perf_strided PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;90;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(threadsafec "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/threadsafec.x")
set_tests_properties(threadsafec PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;91;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(bin "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/bin.x")
set_tests_properties(bin PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;98;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(blktest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/blktest.x")
set_tests_properties(blktest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;99;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(g2test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/g2test.x")
set_tests_properties(g2test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;100;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(g3test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/g3test.x")
set_tests_properties(g3test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;101;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ga_shift "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ga_shift.x")
set_tests_properties(ga_shift PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;102;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ghosts "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ghosts.x")
set_tests_properties(ghosts PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;103;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(jacobi "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/jacobi.x")
set_tests_properties(jacobi PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;104;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(mir_perf2 "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/mir_perf2.x")
set_tests_properties(mir_perf2 PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;105;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(mmatrix "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/mmatrix.x")
set_tests_properties(mmatrix PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;106;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(mulmatpatch "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/mulmatpatch.x")
set_tests_properties(mulmatpatch PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;107;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nbtest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nbtest.x")
set_tests_properties(nbtest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;108;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nb2test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nb2test.x")
set_tests_properties(nb2test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;109;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ndim "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ndim.x")
set_tests_properties(ndim PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;110;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(patch "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/patch.x")
set_tests_properties(patch PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;111;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(patch2 "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/patch2.x")
set_tests_properties(patch2 PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;112;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(patch_enumf "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/patch_enumf.x")
set_tests_properties(patch_enumf PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;113;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(perfmod "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/perfmod.x")
set_tests_properties(perfmod PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;114;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(perform "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/perform.x")
set_tests_properties(perform PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;115;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(perf "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/perf.x")
set_tests_properties(perf PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;116;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(pg2test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/pg2test.x")
set_tests_properties(pg2test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;117;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(pgtest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/pgtest.x")
set_tests_properties(pgtest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;118;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(scan "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/scan.x")
set_tests_properties(scan PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;119;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(sparse "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/sparse.x")
set_tests_properties(sparse PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;121;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(sprsmatmult "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/sprsmatmult.x")
set_tests_properties(sprsmatmult PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;122;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(sprs_testf "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/sprs_testf.x")
set_tests_properties(sprs_testf PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;123;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(stride "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/stride.x")
set_tests_properties(stride PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;124;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(test "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/test.x")
set_tests_properties(test PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;125;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testmatmult "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testmatmult.x")
set_tests_properties(testmatmult PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;126;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testsolve "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testsolve.x")
set_tests_properties(testsolve PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;127;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(overlay "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/overlay.x")
set_tests_properties(overlay PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;128;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(testeig "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/testeig.x")
set_tests_properties(testeig PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;129;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(simple_groups "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/simple_groups.x")
set_tests_properties(simple_groups PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;131;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(simple_groups_comm "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/simple_groups_comm.x")
set_tests_properties(simple_groups_comm PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;132;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nga-onesided "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "2" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nga-onesided.x")
set_tests_properties(nga-onesided PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;168;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nga-patch "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "1" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nga-patch.x")
set_tests_properties(nga-patch PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;169;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nga-periodic "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nga-periodic.x")
set_tests_properties(nga-periodic PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;170;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nga-scatter "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nga-scatter.x")
set_tests_properties(nga-scatter PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;171;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(ngatest "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "1" "/home/d3g293/ga-oshmem/build_shmem/global/testing/ngatest.x")
set_tests_properties(ngatest PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;172;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
add_test(nga-util "/home/d3g293/MPI/openmpi-5.0.8/install/bin/mpiexec" "-n" "4" "/home/d3g293/ga-oshmem/build_shmem/global/testing/nga-util.x")
set_tests_properties(nga-util PROPERTIES  _BACKTRACE_TRIPLES "/home/d3g293/ga-oshmem/cmake/ga-utils.cmake;77;add_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;173;ga_add_parallel_test;/home/d3g293/ga-oshmem/global/testing/CMakeLists.txt;0;")
